# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8bfe7aa8320ef3d9f209cb3c649774750749099622c20abbd3897cbecbfc9e64097c4fb95e87ea349cd47bded1f623c37a2b8eb098981f16e311c8c73bf80e8

test:
  secret_key_base: 8a66f76e2ef9b35f28ef08c13366f23bfa911ed3be6553fa97ae3a5a23e6757c5917f5ebb93d6119eb646ce06f77317d2aa82b562fa6665793ab8566eaaf4473

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
